package vistas;

import atributos.AttrPersona;
import controlador.CtrUsuarios;
import modelos.ModUsuarios;
import utilidades.EstilosDeTablas;

public class VistaMostrarUsuariosReportados extends javax.swing.JPanel {

    public static int id = 0;

    public VistaMostrarUsuariosReportados() {
        initComponents();
        AttrPersona attr = new AttrPersona();
        ModUsuarios modData = new ModUsuarios();
        CtrUsuarios ctr = new CtrUsuarios(attr, modData, this,"");
        ctr.listarUsuariosReportados();
        
        EstilosDeTablas estilos = new EstilosDeTablas();
        estilos.pintar(tablaUsuariosReportados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuariosReportados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaUsuariosReportados.setBackground(new java.awt.Color(255, 255, 255));
        tablaUsuariosReportados.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tablaUsuariosReportados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuariosReportados.setRowHeight(40);
        tablaUsuariosReportados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosReportadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuariosReportados);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 122, 206));
        jLabel2.setText("Usuarios reportados 👇");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 824, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaUsuariosReportadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosReportadosMouseClicked
//        int fila = tablaAbogados.getSelectedRow();
//        if (fila >= 0) {
//            id = Integer.parseInt(tablaAbogados.getValueAt(fila, 0).toString());
//            VistaMostrarArticulos articulos  = new VistaMostrarArticulos();
//            articulos.idArticulo = id;
//            articulos.lblTitulo.setText("ARTICULOS DE LA CATEGORIA "+tablaAbogados.getValueAt(fila, 1).toString());
//             
//            new CambiarPanel(window, articulos);
//        }
    }//GEN-LAST:event_tablaUsuariosReportadosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablaUsuariosReportados;
    // End of variables declaration//GEN-END:variables
}
