package vistas;

import atributos.AttrEstadisticaArticulos;
import controlador.CtrEstadisticaArticulos;
import modelos.ModEstadisticaArticulos;

public class VistaEstadisticaArticulos extends javax.swing.JPanel {

    public static int id = 0;

    public VistaEstadisticaArticulos() {
        initComponents();
        AttrEstadisticaArticulos attr = new AttrEstadisticaArticulos();
        ModEstadisticaArticulos modData = new ModEstadisticaArticulos();
        CtrEstadisticaArticulos ctr = new CtrEstadisticaArticulos(attr, modData, this);
        ctr.listarPorArticulo();
        ctr.listarPorCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPorArticulos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPorCategorias = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaPorArticulos.setBackground(new java.awt.Color(255, 255, 255));
        tablaPorArticulos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tablaPorArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPorArticulos.setRowHeight(40);
        tablaPorArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPorArticulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPorArticulos);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 66, 66));
        jLabel2.setText("POR ÁRTICULOS");

        tablaPorCategorias.setBackground(new java.awt.Color(255, 255, 255));
        tablaPorCategorias.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tablaPorCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPorCategorias.setRowHeight(40);
        tablaPorCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPorCategoriasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPorCategorias);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 66, 66));
        jLabel3.setText("POR CATEGORÍAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPorArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPorArticulosMouseClicked
//        int fila = tablaAbogados.getSelectedRow();
//        if (fila >= 0) {
//            id = Integer.parseInt(tablaAbogados.getValueAt(fila, 0).toString());
//            VistaMostrarArticulos articulos  = new VistaMostrarArticulos();
//            articulos.idArticulo = id;
//            articulos.lblTitulo.setText("ARTICULOS DE LA CATEGORIA "+tablaAbogados.getValueAt(fila, 1).toString());
//             
//            new CambiarPanel(window, articulos);
//        }
    }//GEN-LAST:event_tablaPorArticulosMouseClicked

    private void tablaPorCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPorCategoriasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaPorCategoriasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tablaPorArticulos;
    public static javax.swing.JTable tablaPorCategorias;
    // End of variables declaration//GEN-END:variables
}
